### ISSUE TITLE
Unclear syntax in calculation formulas in scientific model.

### ISSUE THREAD

**Issue by cuvar** [marmelab/greenframe-cli#38]
I've been reading through your [scientific model](https://github.com/marmelab/greenframe-cli/blob/main/src/model/README.md) and I came across some irritating syntax. So the following paragraph
> - cpuWh = `pue` _ avg(`cpu.totalUsageInUserMode` + `cpu.totalUsageInKernelMode`) _ `config.CPU` / 3600
> - memWh = `pue` _ avg(`memory.usage`) _ `config.MEM` \* `totalTime` / 3600
> - diskWh = `pue` _ avg(`io.totalByte`) _ `config.DISK`
> - networkWh = avg(`network.totalReceived` + `network.totalTransmitted`) \* `config.NETWORK` / 2
> - screenWh = avg(`userTime`) \* `config.SCREEN` / 3600

contains this specific expressions:
 > `pue` _ ...

I'm unsure what this expression should be saying. E.g. is it a multiplication or division? However, this might as well be missing knowledge on my side for scientific maths. I would appreciate some clarification here! 
Thanks

**Comment by guilbill** [comment]
The PUE is the Power Usage Effectiveness : https://en.wikipedia.org/wiki/Power_usage_effectiveness

**Comment by fzaninotto** [comment]
Sorry for the unclear syntax, I've just fixed it.
