### ISSUE TITLE
Retrieve much more details than the estimated footprint from greenframe-cli

### ISSUE THREAD

**Issue by dennewbie** [marmelab/greenframe-cli#53]
Hi there,

I was just wondering if currently there is a way to retrieve the details provided by the GreenFrame online report at https://app.greenframe.io/YOUR_ANALYSIS_ID, directly from the results of the following command:

`GREENFRAME_SECRET_TOKEN=your-token-here greenframe analyze https://marmelab.com`

Can anyone of the dev just confirm that in this moment this kind of functionality is not available?

With advanced metrics/details, I'm referring to this data:
![image](https://github.com/marmelab/greenframe-cli/assets/41870472/d2a30029-1f18-4d2e-a5eb-341565421584)

Thank you in advance.

**Comment by fzaninotto** [comment]
You're right, the CLI currently doesn't output these details. It only sends them to the greenframe.io service when you provide a token. 

This is for legacy reasons - the CLI was designed to work with the greenframe.io service before it was open-sourced. In the future, we'd like to expose a more detailed report directly in the CLI, and to offer the ability to output a structured report in JSON.

If you feel like working on it, feel free to submit a PR!
