### ISSUE TITLE
Unexpected token 'const'

### ISSUE THREAD

**Issue by mgifford** [marmelab/greenframe-cli#64]
Just trying to follow the usage model [https://github.com/marmelab/greenframe-cli/tree/main#usage](https://github.com/marmelab/greenframe-cli/tree/main#usage)  
  
in greenframe-cli/1.6.8 darwin-arm64 node-v16.20.1  
  
I'm getting this error with `% greenframe open https://marmelab.com ./my-scenario.js`

```
Running 1 scenarios...
❌ Error : main scenario
Unexpected token 'const'
```

I'm just using the basic scenario provided `% cat my-scenario.js        `                    

```
// in my-scenario.js
const scenario = async (page) => {
    await page.goto('', { waitUntil: 'networkidle' }); // Go to the baseUrl
    await page.waitForTimeout(3000); // Wait for 3 seconds
    await page.scrollToElement('footer'); // Scroll to the footer (if present)
    await page.waitForNetworkIdle(); // Wait every request has been answered as a normal user.
};

module.exports = scenario;
```

**Comment by erwanMarmelab** [comment]
Hello,

Sorry for the confusion. The current README has been updated and corresponds to a future version of greenframe-cli which has not been released yet. Here is the actual and official documentation website corresponding to the current released version : 
https://docs.greenframe.io/scenario

Kind regards.
