### ISSUE TITLE
Could not connect to Docker daemon on undefined:undefined

### ISSUE THREAD

**Issue by henrik-endl** [marmelab/greenframe-cli#82]
Hi,

i try to run greenframeio on a MacOS, i'd installed vi Curl and ran the example code, i recevie following error,

git:(main) greenframe analyze https://marmelab.com
✔ Check configuration file
✔ Retrieving Git information
❯ Analysis is in progress locally
  ✔ Docker version 26.0.0, build 2ae903e
  ✖ Could not connect to Docker daemon on undefined:undefined

❌ Failed!
ConfigurationError
Could not connect to Docker daemon on undefined:undefined

Thanks for any help,

kind regards 
Henrik

**Comment by fzaninotto** [comment]
See https://github.com/marmelab/greenframe-cli/issues/60#issuecomment-1701466919
